# Docker Compose template for vLLM server
# This file is used by launcher.py to generate per-config compose files

services:
  vllm:
    image: vllm/vllm-openai:v0.10.0
    container_name: vllm-server
    ports:
      - "8000:8000"
    ipc: host
    restart: "no"
    volumes:
      - /opt/hf_cache:/root/.cache/huggingface
    environment:
      ${ENV_VARS}
    command:
      - --model
      - ${MODEL_ID}
      - --served-model-name
      - ${SERVED_MODEL_NAME}
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --max-model-len
      - "${MAX_MODEL_LEN}"
      - --gpu-memory-utilization
      - "${GPU_MEMORY_UTILIZATION}"
      ${EXTRA_ARGS}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

